"""
Shared Tools: Policy generation functions used by all frameworks
"""

def tool_research_wfh_policy(input_text: str) -> str:
    """
    Research WFH policy best practices for India 2026.
    
    Returns key points about eligibility, hours, security, compliance, etc.
    """
    return (
        "WFH Policy Research Points (India 2026):\n"
        "\n"
        "1. Eligibility & Approval:\n"
        "   - Role-based eligibility (exceptions for customer-facing roles)\n"
        "   - Manager + HR approval required\n"
        "   - Probation period restrictions\n"
        "   - Performance-based eligibility review\n"
        "\n"
        "2. Working Hours & Attendance:\n"
        "   - Core hours: 10 AM - 4 PM IST (mandatory availability)\n"
        "   - Daily check-in/check-out via HRMS\n"
        "   - Time tracking for billable hours\n"
        "   - Response time expectations (within 2 hours during core hours)\n"
        "\n"
        "3. Data Security & Device Rules:\n"
        "   - VPN mandatory for all company systems access\n"
        "   - Company-managed devices preferred (BYOD with MDM)\n"
        "   - Secure Wi-Fi required (no public hotspots)\n"
        "   - No shared/public devices for work\n"
        "   - Encrypted storage for sensitive data\n"
        "\n"
        "4. Compliance & Legal:\n"
        "   - IT Act 2000 compliance (data protection)\n"
        "   - GDPR considerations for international data\n"
        "   - Confidentiality agreements enforcement\n"
        "   - Audit trail requirements\n"
        "   - Disciplinary actions for violations\n"
        "\n"
        "5. Expense Reimbursement:\n"
        "   - Internet stipend: ₹1000/month\n"
        "   - Office equipment: up to ₹15,000 (one-time)\n"
        "   - Electricity allowance: ₹500/month\n"
        "   - Receipt submission required\n"
        "\n"
        "6. Exceptions & Escalations:\n"
        "   - Critical roles may require on-site presence\n"
        "   - Incident response: 4-hour on-site SLA\n"
        "   - Client meetings: on-site as needed\n"
        "   - Manager escalation for exceptions\n"
        "\n"
        "7. Review & Versioning:\n"
        "   - Quarterly policy review\n"
        "   - Change log maintenance\n"
        "   - Employee acknowledgement required\n"
        "   - Annual compliance audit"
    )


def tool_draft_policy(research_points: str) -> str:
    """
    Draft a structured WFH policy based on research points.
    """
    return (
        "DRAFT: Work From Home Policy 2026 (India)\n"
        "==========================================\n"
        "\n"
        "Purpose:\n"
        "This policy defines eligibility, approval workflow, work expectations, "
        "security requirements, and compliance obligations for employees working remotely.\n"
        "\n"
        "Scope:\n"
        "Applies to all permanent employees post-probation, subject to role suitability "
        "and manager approval.\n"
        "\n"
        "Research Points Incorporated:\n"
        f"{research_points}\n"
        "\n"
        "Policy Structure:\n"
        "1. Eligibility & Approval Process\n"
        "2. Working Hours & Attendance Expectations\n"
        "3. Information Security & Device Management\n"
        "4. Confidentiality & Compliance Requirements\n"
        "5. Expense Reimbursement Guidelines\n"
        "6. Exceptions & Escalation Process\n"
        "7. Policy Review & Version Control\n"
        "\n"
        "Next Steps:\n"
        "- Compliance review required\n"
        "- Legal approval needed\n"
        "- Format for final distribution"
    )


def tool_compliance_check(draft: str) -> str:
    """
    Review draft policy for compliance gaps and provide recommendations.
    """
    compliance_notes = [
        "Add explicit confidentiality clause with disciplinary actions for breaches",
        "Include data retention policy and access control expectations",
        "Specify incident reporting SLA (within 24 hours for security breaches)",
        "Clarify reimbursement caps with approval hierarchy",
        "Add clause for equipment return upon termination",
        "Include background verification requirements for home workspace",
        "Specify jurisdiction for legal disputes (Indian courts)",
        "Add non-discrimination clause (WFH access must be equitable)",
        "Include ergonomic guidelines to prevent workplace injury claims",
        "Specify insurance coverage for home office accidents"
    ]
    
    return (
        "COMPLIANCE REVIEW NOTES:\n"
        "========================\n"
        "\n"
        "Required Additions:\n"
        + "\n".join([f"  • {note}" for note in compliance_notes]) +
        "\n\n"
        "Legal Considerations:\n"
        "  • IT Act 2000 (Section 43A) - Data protection obligations\n"
        "  • Industrial Disputes Act 1947 - Employee rights\n"
        "  • Shops and Establishments Act - Working hours compliance\n"
        "  • ISO 27001 alignment for information security\n"
        "\n"
        "Risk Mitigation:\n"
        "  • Annual WFH agreement renewal\n"
        "  • Periodic home workspace audits\n"
        "  • Cyber insurance coverage verification\n"
        "  • Employee training on data security (mandatory)\n"
        "\n"
        "Status: DRAFT - Requires legal sign-off before publication"
    )


def tool_finalize_policy(draft: str, compliance_notes: str) -> str:
    """
    Create final formatted policy incorporating compliance feedback.
    """
    return (
        "═══════════════════════════════════════════════════════════════\n"
        "           WORK FROM HOME POLICY 2026 (INDIA)\n"
        "═══════════════════════════════════════════════════════════════\n"
        "\n"
        "Document Version: 1.0\n"
        "Effective Date: January 1, 2026\n"
        "Last Reviewed: January 2026\n"
        "Policy Owner: Human Resources\n"
        "Approved By: Chief Human Resources Officer\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "1. ELIGIBILITY & APPROVAL WORKFLOW\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "Eligibility Criteria:\n"
        "  • Permanent employees post-probation period\n"
        "  • Role suitable for remote work (non-customer-facing)\n"
        "  • Satisfactory performance rating (last 2 reviews)\n"
        "  • Secure home workspace meeting company standards\n"
        "\n"
        "Approval Process:\n"
        "  1. Employee submits WFH request via HRMS portal\n"
        "  2. Manager reviews and approves/rejects within 5 business days\n"
        "  3. HR validates eligibility and workspace compliance\n"
        "  4. IT provisions secure access (VPN, devices)\n"
        "  5. Employee signs WFH agreement (annual renewal required)\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "2. WORKING HOURS & ATTENDANCE\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "Core Hours:\n"
        "  • Mandatory availability: 10:00 AM - 4:00 PM IST\n"
        "  • Daily check-in/check-out via HRMS\n"
        "  • Time tracking for billable hours (client projects)\n"
        "  • Response time: Within 2 hours during core hours\n"
        "\n"
        "Attendance Expectations:\n"
        "  • Calendar must reflect availability status\n"
        "  • Leave requests follow standard approval process\n"
        "  • No WFH during sick leave (must log sick leave)\n"
        "  • Unscheduled absence: Notify manager within 1 hour\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "3. DATA SECURITY & DEVICE MANAGEMENT\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "Mandatory Security Measures:\n"
        "  • VPN connection required for all company system access\n"
        "  • Company-managed devices preferred (laptops, monitors)\n"
        "  • BYOD devices: MDM enrollment mandatory\n"
        "  • Secure Wi-Fi: WPA3 encryption, no public hotspots\n"
        "  • Screen lock: Auto-lock after 5 minutes of inactivity\n"
        "  • Encrypted storage for sensitive/confidential data\n"
        "\n"
        "Prohibited Activities:\n"
        "  • Using shared or public devices for work\n"
        "  • Accessing company systems from internet cafes\n"
        "  • Sharing login credentials with family members\n"
        "  • Installing unauthorized software on company devices\n"
        "  • Taking company devices outside India without approval\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "4. CONFIDENTIALITY & COMPLIANCE\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "Confidentiality Requirements:\n"
        "  • All confidentiality agreements remain in full force\n"
        "  • Secure handling of physical documents (locked storage)\n"
        "  • Shred confidential papers; do not use home trash\n"
        "  • Video call backgrounds: Neutral/blurred (no sensitive info visible)\n"
        "  • Family members must not access work materials\n"
        "\n"
        "Compliance Obligations:\n"
        "  • IT Act 2000 (Section 43A) - Data protection compliance\n"
        "  • Access controls: Least-privilege principle\n"
        "  • Audit logs: All system access tracked and reviewed\n"
        "  • Annual security training: Mandatory completion\n"
        "  • Incident reporting: Within 24 hours of discovery\n"
        "\n"
        "Disciplinary Actions:\n"
        "  • Policy violations may result in:\n"
        "    - Warning (first offense)\n"
        "    - WFH privilege revocation (repeated violations)\n"
        "    - Termination (serious breaches: data theft, security compromise)\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "5. EXPENSE REIMBURSEMENT\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "Monthly Allowances:\n"
        "  • Internet stipend: ₹1,000/month\n"
        "  • Electricity allowance: ₹500/month\n"
        "  • Auto-credited to salary (taxable)\n"
        "\n"
        "One-Time Equipment:\n"
        "  • Office furniture: Up to ₹15,000 (chair, desk)\n"
        "  • Requires manager pre-approval\n"
        "  • Receipts must be submitted within 30 days\n"
        "  • Equipment remains employee property\n"
        "\n"
        "Reimbursement Process:\n"
        "  1. Submit claim via expense management system\n"
        "  2. Attach original receipts (digital copies accepted)\n"
        "  3. Manager approval within 5 business days\n"
        "  4. Finance processes within 15 business days\n"
        "\n"
        "Non-Reimbursable Expenses:\n"
        "  • Personal mobile phone bills\n"
        "  • Coffee, snacks, meals\n"
        "  • Transportation to occasional office visits\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "6. ESCALATIONS & EXCEPTIONS\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "On-Site Requirements:\n"
        "  • Critical roles: May require on-site presence (defined by dept)\n"
        "  • Client meetings: On-site as requested by client\n"
        "  • Incident response: 4-hour on-site SLA for P1 incidents\n"
        "  • Team events: Quarterly all-hands (attendance mandatory)\n"
        "\n"
        "Exception Requests:\n"
        "  • WFH from location outside approved city: Requires HR approval\n"
        "  • Extended WFH (>3 months continuously): Requires dept head approval\n"
        "  • International travel during WFH: Requires legal clearance\n"
        "\n"
        "Escalation Path:\n"
        "  • Policy interpretation: Contact HR Business Partner\n"
        "  • Technical issues: IT Service Desk (helpdesk@company.com)\n"
        "  • Security incidents: CISO office (security@company.com)\n"
        "  • Grievances: Follow standard grievance redressal process\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "7. POLICY REVIEW & VERSIONING\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "Review Schedule:\n"
        "  • Quarterly review by HR Policy Committee\n"
        "  • Annual compliance audit by Internal Audit\n"
        "  • Ad-hoc updates for regulatory changes\n"
        "\n"
        "Change Management:\n"
        "  • All changes tracked in version control log\n"
        "  • Major revisions require employee re-acknowledgement\n"
        "  • 30-day notice for material changes\n"
        "  • Policy published on company intranet\n"
        "\n"
        "Employee Acknowledgement:\n"
        "  • Mandatory acknowledgement via HRMS (digital signature)\n"
        "  • Annual re-acknowledgement required\n"
        "  • New hires: Acknowledgement during onboarding\n"
        "  • Non-acknowledgement: WFH request auto-rejected\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "COMPLIANCE REVIEW SUMMARY\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        f"{compliance_notes}\n"
        "\n"
        "───────────────────────────────────────────────────────────────\n"
        "DISCLAIMER\n"
        "───────────────────────────────────────────────────────────────\n"
        "\n"
        "This policy is subject to change. The company reserves the right to\n"
        "modify, suspend, or terminate the WFH program at its discretion.\n"
        "WFH is a privilege, not a right, and may be revoked for business needs.\n"
        "\n"
        "For questions, contact: hr-policy@company.com\n"
        "\n"
        "═══════════════════════════════════════════════════════════════\n"
        "                    END OF DOCUMENT\n"
        "═══════════════════════════════════════════════════════════════\n"
    )


# User request constant
USER_REQUEST = "Create a Work From Home policy for 2026 (India) with key rules + compliance notes."